### PR TITLE
feat(google-cloud-sdk): support arm64 architectures

### PR DESCRIPTION
**Pull request by ahrex**

### CODE REVIEW

**Comment by sudoforge** [comment]
thanks for the contribution! i've been away for a while and am just getting back into the swing of things.

can you please use the instructions in the readme to set up the commit hooks, and resubmit this change?

**Review by sudoforge — CHANGES_REQUESTED** [review]
thanks for the contribution! i've been away for a while and am just getting back into the swing of things.

can you please use the instructions in the readme to set up the commit hooks, and resubmit this change?

**Comment by ahrex** [comment]
Updated, thanks!

**Comment by sudoforge** [comment]
i'm going to be pulling this in prior to updating the package to get it back in sync with upstream releases. thanks again!

**Pull request closed without merging**
