### PR TITLE
Lower priorities of gcloud binaries

### PR DESCRIPTION
**Pull request by glutamatt**
kubectl of gcloud is outdated compared to https://aur.archlinux.org/packages/kubectl-bin 
i want to prioritze binaries i've installed in default paths

### CODE REVIEW

**Comment by sudoforge** [comment]
`kubectl` is not included with `google-cloud-sdk` and is not present in the `./bin` directory of the project. Please see [sudoforge/pkgbuilds#12](https://github.com/sudoforge/pkgbuilds/issues/12) and https://issuetracker.google.com/issues/151861786.

**Comment by glutamatt** [comment]
thanks for your feedback.
i hope it's something specific to my setup : please have a look
image

**Comment by glutamatt** [comment]
the dates of files give clue about something related to an old install poorly cleaned

**Comment by sudoforge** [comment]
@glutamatt I checked the histories for each of `kubectl`, `kubectl-bin`, and `google-cloud-sdk` for commits around that date. None of them install `kubectl` to `/opt/google-cloud-sdk/bin`.

Can you do me a favor and check to see if Pacman thinks a package owns them?

```
pacman -Fo /opt/google-cloud-sdk/bin/kubectl
```

**Comment by sudoforge** [comment]
@glutamatt I checked the histories for each of `kubectl`, `kubectl-bin`, and `google-cloud-sdk` for commits around that date. None of them install `kubectl` to `/opt/google-cloud-sdk/bin`.

Can you do me a favor and check to see if Pacman thinks a package owns them?

```
pacman -F /opt/google-cloud-sdk/bin/kubectl
```

**Comment by glutamatt** [comment]
image
_**nothing**_ 

but as i said, i removed those old binaries 4 days ago, after i found out binaries were outdated

**Comment by glutamatt** [comment]
maybe i did [that](https://kubernetes.io/docs/setup/production-environment/turnkey/gce/#installing-the-kubernetes-command-line-tools-on-your-workstation) on september 2019 but I can't remember 👴🤓

**Comment by sudoforge** [comment]
> but as i said, i removed those old binaries 4 days ago, after i found out binaries were outdated

Unless you have also ran `sudo pacman -Fy` (or have a hook, timer, or other such mechanism to do this automatically), then your **files database** could have still contained the information about any custom package you had that owned those files.

> maybe i did that on september 2019 but I can't remember 
> 
> or maybe this install is done automatically on some performed action i did , for example an app engine deployment 

I think it is likely some custom action you took. Commit `e01da1e449882ad8e4fe590b01cd09624b58143a` was made in August 2018, which was a key commit in the `google-cloud-sdk` package as it slimmed down the package (removing most components). One of the key changes that was made was switching the source from the "standard" download to the "for_packagers" download, which, among other things, has the ability to disable using the in-built component manager to install additional components.

There have been various iterations of [a pinned comment](https://aur.archlinux.org/packages/google-cloud-sdk/#pinned-659642) describing different workarounds for this on the package page since that commit was introduced. It is quite possible that you modified the `google-cloud-sdk` installation to allow yourself to manage additional components via the `gcloud` executable.

> in that case, it could be an issue because of the eventual old version of the binary + path priority configured by package kubectl-bin

I find this less likely, as the `kubectl-bin` package, at least in the commits leading up to the dates from your screenshot, did not install the executable into `/opt/google-cloud-sdk/bin`. I have personally always used the `kubectl-bin` package myself, and would have definitely noticed this :)

---

Anyhow, removing the executables was the right call -- you should make sure you remove the `~/.local/bin/kubectl` wrapper you have (along with any shell aliases you may have set). As long as you aren't overriding anything in particular, you should be good to go!

**Comment by sudoforge** [comment]
Also, for posterity's sake, there is a (low-priority) issue somewhat related to this: https://github.com/sudoforge/pkgbuilds/issues/19

**Comment by sudoforge** [comment]
Also, I should note that even if you modified the `google-cloud-sdk` package to allow yourself to manage additional components via `gcloud`, the versioned executables look a little funky to me and I would question whether or not the in-built component manager was responsible for the `kubectl.1.1{3,4,5}` executables. The component manager uses a manifest to track the installed version among other metadata, and wouldn't need to do this filename-based version pinning.

**Comment by glutamatt** [comment]
> Unless you have also ran sudo pacman -Fy (or ..

nope, nothing about that 

> you should make sure you remove ...

i did 👌 

thanks a lot for your investigation and the great and useful work managing `google-cloud-sdk` 👏

**Pull request closed without merging**
