### PR TITLE
google-cloud-sdk: update upstream: 337.0.0

### PR DESCRIPTION
**Pull request by miraclx**
Updated packages:
  - google-cloud-sdk
  - google-cloud-sdk-datastore-emulator
  - google-cloud-sdk-app-engine-python
  - google-cloud-sdk-app-engine-python-extras
  - google-cloud-sdk-app-engine-java

### CODE REVIEW

**Comment by sudoforge** [comment]
Thanks for this, I've been caught up in other things this week.

Would you mind rebasing these commits into a single one, with a commit message that follows the same pattern in this repository?

```
$ git checkout gcp-337

$ git rebase -i HEAD~5
```

Rebase instructions:

```
reword 99e9805 update google-cloud-sdk
fixup f3f1ad8 update google-cloud-sdk-datastore-emulator
fixup ad726d2 update google-cloud-sdk-app-engine-python
fixup c27e0c4 update google-cloud-sdk-app-engine-python-extras
fixup 27ef73a update google-cloud-sdk-app-engine-java
```

`reword` will open up your editor and allow you to change the commit message, and `fixup` will meld the commits into the former one, discarding their individual commit messages.

**Comment by sudoforge** [comment]
Given that it appears you are in a UTC+0100 (based on the commit and author dates on your commits), I'm going to go ahead and make these changes myself (in a unique commit), but will add a `Co-authored-by` trailer with the commit author information in your tree.

**Comment by miraclx** [comment]
You don't want to just squash merge on your end?

**Comment by sudoforge** [comment]
Apologies, I didn't see your last comment until now. That is not enabled for this repository.

**Pull request closed without merging**
